name: UPM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Subtree Sync
        uses: xedi/action-subtree-sync@1.0.0
        with:
          subtree: 'NagaChiang/Timespawn.Core'
          subtree_deploy_key: ${{ secrets.DEPLOY_KEY }}
          split_prefix: 'Assets'


